### ISSUE TITLE
Constant warnings in logs since upgraded to 1.5

### ISSUE THREAD

**Issue by Yajo** [containous/traefik#2762]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

I upgraded from traefik 1.4 to 1.5, just by switching the docker image version and adding `--ACME.HTTPChallenge.entryPoint=http` to boot cli args.

### What did you expect to see?

All working fine again, but with http-01 enabled.

### What did you see instead?

All working fine, but traefik logs are **full** of this message every 1-3 lines:

    WARN[2018-01-25T08:55:03Z] Upstream ResponseWriter of type *negroni.responseWriter does not implement http.CloseNotifier. Returning dummy channel.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.0
Codename:     cancoillotte
Go version:   go1.9.2
Built:        2018-01-23_04:42:32PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```shell
traefik 
--ACME.ACMELogging 
--ACME.CAServer=https://acme-v01.api.letsencrypt.org/directory 
--ACME.Email=****
--ACME.EntryPoint=https 
--ACME.HTTPChallenge.entryPoint=http 
--ACME.OnDemand 
--ACME.OnHostRule 
--ACME.Storage=/etc/traefik/acme/acme.json 
--DefaultEntryPoints=http,https 
--Docker 
--Docker.Endpoint=http://dockersocket:2375 
--Docker.ExposedByDefault=false 
--Docker.Watch 
--EntryPoints=Name:http Address::80 Redirect.EntryPoint:https Compress:on 
--EntryPoints=Name:https Address::443 TLS Compress:on 
--LogLevel=INFO
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```shell
INFO[2018-01-25T09:08:48Z] vulcand/oxy/forward/http: Round trip: http://**.**.**.**:****, code: 200, Length: 142, duration: 50.022664687s tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:www.*******.com 
DEBU[2018-01-25T09:08:48Z] vulcand/oxy/forward/http: completed ServeHttp on request  Request="{"Method":"POST","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"**.**.**.**:****","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["application/json, text/javascript, */*; q=0.01"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["es-ES,es;q=0.8"],"Content-Length":["150"],"Content-Type":["application/json"],"Cookie":[**CENSORED**]},"ContentLength":150,"TransferEncoding":null,"Host":"www.*******.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"**.**.**.**:****","RequestURI":"/longpolling/poll","TLS":null}"
DEBU[2018-01-25T09:08:48Z] vulcand/oxy/forward: completed ServeHttp on request  Request="{"Method":"POST","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"**.**.**.**:****","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["application/json, text/javascript, */*; q=0.01"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["es-ES,es;q=0.8"],"Content-Length":["150"],"Content-Type":["application/json"],"Cookie":[**CENSORED**]},"ContentLength":150,"TransferEncoding":null,"Host":"www.*******.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"**.**.**.**:****","RequestURI":"/longpolling/poll","TLS":null}"
DEBU[2018-01-25T09:08:48Z] vulcand/oxy/roundrobin/rr: competed ServeHttp on request  Request="{"Method":"POST","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/longpolling/poll","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["application/json, text/javascript, */*; q=0.01"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["es-ES,es;q=0.8"],"Content-Length":["150"],"Content-Type":["application/json"],"Cookie":[**CENSORED**]},"ContentLength":150,"TransferEncoding":null,"Host":"www.*******.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"**.**.**.**:****","RequestURI":"/longpolling/poll","TLS":null}"
DEBU[2018-01-25T09:08:48Z] vulcand/oxy/roundrobin/rr: begin ServeHttp on request  Request="{"Method":"POST","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/longpolling/poll","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["application/json, text/javascript, */*; q=0.01"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["es-ES,es;q=0.8"],"Content-Length":["151"],"Content-Type":["application/json"],"Cookie":[**CENSORED**]},"ContentLength":151,"TransferEncoding":null,"Host":"www.*******.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"**.**.**.**:****","RequestURI":"/longpolling/poll","TLS":null}"
DEBU[2018-01-25T09:08:48Z] vulcand/oxy/roundrobin/rr: Forwarding this request to URL  Request="{"Method":"POST","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/longpolling/poll","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["application/json, text/javascript, */*; q=0.01"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["es-ES,es;q=0.8"],"Content-Length":["151"],"Content-Type":["application/json"],"Cookie":[**CENSORED**]},"ContentLength":151,"TransferEncoding":null,"Host":"www.*******.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"**.**.**.**:****","RequestURI":"/longpolling/poll","TLS":null}" ForwardURL=http://**.**.**.**:****
DEBU[2018-01-25T09:08:48Z] vulcand/oxy/forward: begin ServeHttp on request  Request="{"Method":"POST","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"**.**.**.**:****","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["application/json, text/javascript, */*; q=0.01"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["es-ES,es;q=0.8"],"Content-Length":["151"],"Content-Type":["application/json"],"Cookie":[**CENSORED**]},"ContentLength":151,"TransferEncoding":null,"Host":"www.*******.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"**.**.**.**:****","RequestURI":"/longpolling/poll","TLS":null}"
DEBU[2018-01-25T09:08:48Z] vulcand/oxy/forward/http: begin ServeHttp on request  Request="{"Method":"POST","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"**.**.**.**:****","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["application/json, text/javascript, */*; q=0.01"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["es-ES,es;q=0.8"],"Content-Length":["151"],"Content-Type":["application/json"],"Cookie":[**CENSORED**]},"ContentLength":151,"TransferEncoding":null,"Host":"www.*******.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"**.**.**.**:****","RequestURI":"/longpolling/poll","TLS":null}"
WARN[2018-01-25T09:08:48Z] Upstream ResponseWriter of type *negroni.responseWriter does not implement http.CloseNotifier. Returning dummy channel. 
DEBU[2018-01-25T09:08:50Z] vulcand/oxy/roundrobin/rr: begin ServeHttp on request  Request="{"Method":"POST","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/web/dataset/search_read","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["application/json, text/javascript, */*; q=0.01"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["es-ES,es;q=0.8"],"Content-Length":["539"],"Content-Type":["application/json"],"Cookie":[**CENSORED**]},"ContentLength":539,"TransferEncoding":null,"Host":"www.*******.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"**.**.**.**:****","RequestURI":"/web/dataset/search_read","TLS":null}"
DEBU[2018-01-25T09:08:50Z] vulcand/oxy/roundrobin/rr: Forwarding this request to URL  Request="{"Method":"POST","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/web/dataset/search_read","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["application/json, text/javascript, */*; q=0.01"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["es-ES,es;q=0.8"],"Content-Length":["539"],"Content-Type":["application/json"],"Cookie":[**CENSORED**]},"ContentLength":539,"TransferEncoding":null,"Host":"www.*******.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"**.**.**.**:****","RequestURI":"/web/dataset/search_read","TLS":null}" ForwardURL=http://**.**.**.**:****
DEBU[2018-01-25T09:08:50Z] vulcand/oxy/forward: begin ServeHttp on request  Request="{"Method":"POST","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"**.**.**.**:****","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["application/json, text/javascript, */*; q=0.01"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["es-ES,es;q=0.8"],"Content-Length":["539"],"Content-Type":["application/json"],"Cookie":[**CENSORED**]},"ContentLength":539,"TransferEncoding":null,"Host":"www.*******.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"**.**.**.**:****","RequestURI":"/web/dataset/search_read","TLS":null}"
DEBU[2018-01-25T09:08:50Z] vulcand/oxy/forward/http: begin ServeHttp on request  Request="{"Method":"POST","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"**.**.**.**:****","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["application/json, text/javascript, */*; q=0.01"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["es-ES,es;q=0.8"],"Content-Length":["539"],"Content-Type":["application/json"],"Cookie":[**CENSORED**]},"ContentLength":539,"TransferEncoding":null,"Host":"www.*******.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"**.**.**.**:****","RequestURI":"/web/dataset/search_read","TLS":null}"
WARN[2018-01-25T09:08:50Z] Upstream ResponseWriter of type *negroni.responseWriter does not implement http.CloseNotifier. Returning dummy channel. 
INFO[2018-01-25T09:08:50Z] vulcand/oxy/forward/http: Round trip: http://**.**.**.**:****, code: 200, Length: 457, duration: 53.425033ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:www.*******.com 
```

**Comment by Juliens** [comment]
The problem is the same in #2760 (just when we activate metrics it panics instead of just log)
Close for duplicate
