### PR TITLE
Update lego

### LINKED ISSUE #5165: Upgrade go-acme/lego to 2.7.1
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [ ] No

### What did you do?

As our Let's Encrypt Certificate expired I investigated that there is a problem with the DNS-Challenge provider we use.

### What did you expect to see?

A proper DNS-Challenge 

### What did you see instead?

An error while talking to the DNS provider

### Output of `traefik version`: 1.7.12

```
time="2019-07-29T06:57:44Z" level=error msg="Error renewing certificate from LE: {*.sub.domain.com []}, acme: Error -> One or more domains had a problem:\n[*.sub.domain.com] [*.sub.domain.com] acme: error presenting token: otc: unable to get zone: Get https://dns.eu-de.otc.t-systems.com/v2/zones?name=sub.domain.com.: net/http: request canceled (Client.Timeout exceeded while awaiting headers)\n"
```

### Suggestion

As this problem has already been addressed in acme-lego (https://github.com/go-acme/lego/issues/902) I would appreciate an upgrade to version v2.7.1

### PR DESCRIPTION
**Pull request by dabeck**
### What does this PR do?

Updates acme-lego to 2.7.2.
Fixes #5165

### Motivation

Issue #5165

### More

- [ ] Added/updated tests
- [ ] Added/updated documentation

### CODE REVIEW

File: Gopkg.toml [hunk 1]
```diff
@@ -194,7 +194,7 @@ required = [
 
 [[constraint]]
   name = "github.com/golang/protobuf"
-  version = "v1.3.0"
```
Comment (dduportal) [inline Gopkg.toml]: Is there a particular reason to do this update here?

Comment (dabeck) [reply Gopkg.toml]: It did not compile with 1.3.0 on my local machine. But I am actually not sure if its a hard requirement.

**Comment by dduportal** [comment]
Hi @dabeck , thanks for this contribution. Could you rebase this PR against the branch `v1.7` please? (as `master` is the "experimental").

(1.7 because it looks like it's not a new feature but a bugfix/dep fix. If I'm wrong and that other maintainers tells its worth a "new" feature, then you'll have to rebase against `v2.0` as 1.7 does not accept new features)

File: Gopkg.toml [hunk 2]
```diff
@@ -180,7 +180,11 @@
 
 [[constraint]]
   name = "github.com/go-acme/lego"
-  version = "2.6.0"
+  version = "2.7.1"
+
+[[constraint]]
```
Comment (dduportal) [inline Gopkg.toml]: What is the reason for adding the protobuf dependency here?

Comment (dabeck) [reply Gopkg.toml]: It won't build anymore because of a sub-dependency. Without protobuf < 1.3 you'll get:
```
---> Making bundle: binary (in .)
# github.com/containous/traefik/vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/common/v1
vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/common/v1/common.pb.go:22:11: undefined: proto.ProtoPackageIsVersion3
# github.com/containous/traefik/vendor/github.com/census-instrumentation/opencensus-proto/gen-go/resource/v1
vendor/github.com/census-instrumentation/opencensus-proto/gen-go/resource/v1/resource.pb.go:21:11: undefined: proto.ProtoPackageIsVersion3
```

**Comment by mmatur** [comment]
Thanks for your PR @dabeck 

I would like to have the review of @ldez

**Comment by drzraf** [comment]
Worth anticipating the update to (to be released) Lego 3.1 which contains useful support for Cloudflare **tokens** (instead of global API key), see https://github.com/go-acme/lego/pull/937
